name: sound_mode
description: A plugin to manage device's sound mode
version: 0.1.2
homepage: https://github.com/TryingOutSomething/sound_mode.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.tryingoutsomething.soundmode.sound_mode
        pluginClass: SoundModePlugin
        # ios:
        # pluginClass: SoundModePlugin